### ISSUE TITLE
Any chance you guys got any apples?

### ISSUE THREAD

**Issue by vnev** [Ztrains/Bazaar#15]
Hi this is Paul from the neighborhood. Wondering if Bazaar is open for some apples?

**Comment by Ztrains** [comment]
More information needed: 

What kind of apples?
How many do you need?

**Comment by vnev** [comment]
Honeydew apples James. I need about 2 pounds of it

**Comment by vnev** [comment]
@Ztrains @shoekla @pvasudha @claker15 @myers259
